# Generated by Django 4.1 on 2022-11-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="file",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auth_id", models.BigIntegerField(null=True, verbose_name="上传者id")),
                ("name", models.CharField(max_length=75, verbose_name="文件名")),
                ("suffix", models.CharField(max_length=75, verbose_name="后缀名")),
                ("address", models.URLField(verbose_name="资源路径")),
                ("size", models.CharField(max_length=30, verbose_name="文件大小")),
                (
                    "department",
                    models.CharField(blank=True, max_length=30, verbose_name="学院"),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=30, verbose_name="学科"),
                ),
                (
                    "readme",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="简介"
                    ),
                ),
                ("download_num", models.IntegerField(default=0, verbose_name="下载量")),
                ("auth_name", models.CharField(max_length=30, verbose_name="上传者昵称")),
            ],
        ),
    ]
