# Generated by Django 4.1 on 2022-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="auth_id",
            field=models.BigIntegerField(default=0, verbose_name="上传者id"),
        ),
        migrations.AlterField(
            model_name="file",
            name="auth_name",
            field=models.CharField(max_length=50, verbose_name="上传者昵称"),
        ),
        migrations.AlterField(
            model_name="file",
            name="department",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="学院"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="subject",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="学科"
            ),
        ),
    ]
