# Generated by Django 4.1 on 2022-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="QQ",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="QQ"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="WeChat",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="WeChat"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatar", verbose_name="头像"
            ),
        ),
    ]
