# Generated by Django 4.1 on 2022-12-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_user_qq_user_wechat_user_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection_post",
            old_name="file_id",
            new_name="fileID",
        ),
        migrations.RenameField(
            model_name="collection_post",
            old_name="user_id",
            new_name="userID",
        ),
        migrations.RenameField(
            model_name="downloadfile_post",
            old_name="file_id",
            new_name="fileID",
        ),
        migrations.RenameField(
            model_name="downloadfile_post",
            old_name="user_id",
            new_name="userID",
        ),
    ]
