# Generated by Django 4.1 on 2022-12-11 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_rename_file_id_collection_post_fileid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="修改时间"),
        ),
    ]
